## Naive Bayes Classifier

In [38]:
import pandas  as pd
import numpy as np
from sklearn import datasets
#load dataset
wine=datasets.load_wine()
print(wine)
#this data set is the result of a chemical analysis
# of wines grown in the same regon in italy
# but derived from three different cultivars
# the analysis determined the quantitities of 13 constitutions found in each of
x=wine.data
print(x[0])
y=wine.target
c=wine.data[0][1:]
c

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

array([1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00, 3.060e+00,
       2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00, 1.065e+03])

In [17]:
from sklearn.model_selection import train_test_split# Give model Selection
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.3,random_state=3)

In [18]:
from sklearn.naive_bayes import GaussianNB
from sklearn.

In [30]:
gnb=GaussianNB()
gnb.fit(X_train,Y_train)
print(X_train[0][1:])

[  1.53   2.29  21.5   86.     2.74   3.15   0.39   1.77   3.94   0.69
   2.84 352.  ]


In [21]:
y_pred=gnb.predict(X_test)


In [37]:
gnb.predict([[1.423e+01,1.710e+00, 2.430e+00, 1.560e+01 ,1.270e+02 ,2.800e+00 ,3.060e+00,
 2.800e-01 ,2.290e+00, 5.640e+00 ,1.040e+00 ,3.920e+00 ,1.065e+03]])

array([0])

In [42]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [43]:
print(confusion_matrix(Y_test,y_pred))
print(accuracy_score(Y_test,y_pred)*100)

[[22  1  0]
 [ 0 18  1]
 [ 0  0 12]]
96.29629629629629


# K-Nearest Neighbor

In [49]:
(160-158)**2

4

In [50]:
(64-58)**2

36

In [51]:
import math

In [52]:
math.sqrt(40)

6.324555320336759

In [53]:
(158-158)**2

0

In [55]:
math.sqrt(1)

1.0

In [57]:
S_data=pd.read_csv('s_data.csv')
S_data

Height  Weight T-Shirt Size
0      158      58            M
1      158      59            M
2      158      63            M
3      160      59            M
4      160      60            M
5      163      60            M
6      163      61            M
7      160      64            L
8      163      64            L
9      165      61            L
10     165      62            L
11     165      65            L
12     168      62            L
13     168      63            L
14     168      66            L
15     170      63            L
16     170      64            L
17     170      68            L

In [61]:
x=S_data[['Height','Weight']]
y=S_data['T-Shirt Size'].

0     M
1     M
2     M
3     M
4     M
5     M
6     M
7     L
8     L
9     L
10    L
11    L
12    L
13    L
14    L
15    L
16    L
17    L
Name: T-Shirt Size, dtype: object

In [62]:
from sklearn.preprocessing import LabelEncoder
lableencoder_Y=LabelEncoder()
Y=lableencoder_Y.fit_transform(y)
print(Y)

[1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]


In [65]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.3,random_state=3)

In [78]:
#import kneatest neighbors classifier model
from sklearn.neighbors import KNeighborsClassifier
#create KNN Classifier
knn=KNeighborsClassifier(n_neighbors=5)
#train the modelusing the training sets
knn.fit(X_train,Y_train)
#predict the responce for test dataset
y_pred=knn.predict(X_test)
print(y_pred)
#model accuracy ,how ofternn is the classifier correct
print("Acuuracy:",accuracy_score(Y_test,y_pred)*100)

['L' 'M' 'M' 'L' 'M' 'L']
Acuuracy: 100.0


In [79]:
knn.predict([[163,64]])

array(['L'], dtype=object)

In [100]:
bd_data=pd.read_csv('bird.csv')
bd_data

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw  \
0      0  80.78  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84   
1      1  88.91  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   
2      2  79.97  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   
3      3  77.65  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   
4      4  62.80  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   
..   ...    ...   ...    ...    ...    ...   ...    ...   ...    ...   ...   
415  415  17.96  1.63  19.25   1.33  18.36  1.54  31.25  1.33  21.99  1.15   
416  416  19.21  1.64  20.76   1.49  19.24  1.45  33.21  1.28  23.60  1.15   
417  417  18.79  1.63  19.83   1.53  20.96  1.43  34.45  1.41  22.86  1.21   
418  418  20.38  1.78  22.53   1.50  21.35  1.48  36.09  1.53  25.98  1.24   
419  419  17.89  1.44  19.26   1.10  17.62  1.34  29.81  1.24  21.69  1.05   

    type  
0     SW  
1     SW  
2     SW  
3     SW  
4     SW  
..   ...  
415   SO  
416   SO  
417   SO  
418   SO  
419   SO  

[420 rows x 12 columns]

In [101]:
bd_data['type']

0      SW
1      SW
2      SW
3      SW
4      SW
       ..
415    SO
416    SO
417    SO
418    SO
419    SO
Name: type, Length: 420, dtype: object

In [102]:
x=bd_data[['huml','humw','ulnal','ulnaw','feml','femw','tibl','tibw','tarl','tarw']]
y=bd_data['type']

In [121]:
from sklearn.preprocessing import LabelEncoder
lableencoder_Y=LabelEncoder()
Y=lableencoder_Y.fit_transform(y)
print(Y)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [104]:
bd_data.isnull().sum()

id       0
huml     0
humw     0
ulnal    0
ulnaw    0
feml     0
femw     0
tibl     0
tibw     0
tarl     0
tarw     0
type     0
dtype: int64

In [110]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.3,random_state=3)

In [112]:
#import kneatest neighbors classifier model
from sklearn.neighbors import KNeighborsClassifier
#create KNN Classifier
knn=KNeighborsClassifier(n_neighbors=5)
#train the modelusing the training sets
knn.fit(X_train,Y_train)
#predict the responce for test dataset
y_pred=knn.predict(X_test)
print(y_pred)
#model accuracy ,how ofternn is the classifier correct
print("Acuuracy:",accuracy_score(Y_test,y_pred)*100)

['SO' 'SW' 'W' 'T' 'SW' 'SW' 'P' 'P' 'SW' 'P' 'SW' 'SO' 'SO' 'SW' 'P' 'R'
 'P' 'W' 'W' 'SO' 'T' 'SO' 'R' 'P' 'SO' 'P' 'P' 'R' 'SO' 'SO' 'SW' 'P'
 'SW' 'SO' 'SO' 'W' 'P' 'W' 'SO' 'R' 'T' 'SW' 'W' 'W' 'R' 'SO' 'R' 'SO'
 'W' 'SW' 'T' 'P' 'SW' 'W' 'W' 'W' 'SW' 'SO' 'T' 'SW' 'P' 'SW' 'SW' 'SW'
 'SW' 'R' 'R' 'SW' 'SO' 'R' 'SO' 'SO' 'SW' 'SW' 'P' 'SW' 'R' 'P' 'SO' 'SO'
 'SO' 'SO' 'SO' 'SO' 'SO' 'SO' 'R' 'SW' 'R' 'P' 'SW' 'R' 'SO' 'SO' 'SO'
 'SO' 'SW' 'W' 'SO' 'SW' 'SO' 'SW' 'SW' 'SW' 'SO' 'SO' 'SW' 'SO' 'P' 'SO'
 'SO' 'SW' 'P' 'T' 'P' 'P' 'R' 'SO' 'SW' 'SW' 'SW' 'SO' 'SO' 'R' 'SW' 'R']
Acuuracy: 72.22222222222221


In [113]:
knn.predict([[80.78,6.68,72.01,4.88,41.81,3.70,5.50,4.03,38.70,3.84]])

array(['SW'], dtype=object)

In [114]:
print(accuracy_score(Y_test,y_pred)*100)

72.22222222222221


In [115]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
# print(X_train)
X_test=sc.transform(X_test)

In [116]:
from sklearn.svm import SVC
classifier=SVC(kernel='linear',random_state=0)
print(classifier.fit(X_train,Y_train))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)


In [117]:
y_pred=classifier.predict(X_test)
print(accuracy_score(Y_test,y_pred)*100)

76.98412698412699


In [120]:
print(dir(pd))

['Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseArray', 'SparseDataFrame', 'SparseDtype', 'SparseSeries', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_lib', '_libs', '_np_version_under1p14', '_np_version_under1p15', '_np_version_under1p16', '_np_version_under1p17', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_rang

In [122]:
23000-14700

8300